### ISSUE TITLE
Compare to color-tabs-regex

### ISSUE THREAD

**Issue by denis-sokolov** [nmai/lucid-tabs#1]
Thank you for your package, it’s pretty cool.
Could you comment on how is your package different from [`color-tabs-regex`](https://github.com/averrin/color-tabs-regex), if at all?

**Comment by nmai** [comment]
@denis-sokolov Thanks, 99% of the credit goes to Graeme (his project here: [Rainbow Tabs](https://github.com/graemeboy/rainbow-tabs)). Lucid is a fork. I just tweaked a few things for my use case and switched to wildcard matching.

The main differences are as follows:
* Lucid only changes filename text color right now, but it would not be difficult to customize other things as well. Out of the box, `color-tabs-regex` only changes the appearance of the tab background and not the text itself.
* Lucid is entirely LESS. It's strictly styles; there's no JavaScript involved. While this simplifies things somewhat, it definitely limits customization options.
* For the reason above, `color-tabs-regex` is a lot more extensible. Furthermore, if I recall correctly, `color-tabs-regex` is actually built to be configurable whereas Lucid will require you to edit the code (not that it's hard).
* Lucid doesn't support regex or any "smart" form of pattern matching, at least not easily. Unless you add support via javascript, you might do something like this for more complex string matching: 
``` 
.charX(@number) when (@number > 0) {
  (~".char@{number}") {
    @adjustedNumber: (@number - 1) *0.2;
    @unitNumber: ~"@{adjustedNumber}s";
    .titel-animation(@unitNumber)
  }
  .charX(@number - 1);
}

.charX(@number) when (@number = 0) {
} 

.charX(6);
```

**Comment by denis-sokolov** [comment]
Right, I see, thank you. I did not know about rainbow tabs, discoverability of modules is tricky, unfortunately. Similarly, I need to choose and compare multiple alternative modules and choose one, so perhaps it would be beneficial to your module to mention what you told me here in the readme. That ways the users will be able to make a call which module to choose.

```md
# Alternatives
This module is an improved version of rainbow-tabs.
If you need more power and customization at the cost of stability, consider color-tabs-regex.
```

My question is answered and I now understand much better what is going on, thank you.

**Comment by nmai** [comment]
Glad to help, and that's an excellent suggestion. This module is something that I modified+published in like an hour and used every single day; since then, I haven't given much thought to improvements. I'd actually like to rewrite this module completely someday (when I have time).
